-- 党费测试数据
-- 假设用户ID为 '1'，可以根据实际情况修改

-- 生成最近30天的党费记录
INSERT INTO dues_payments (id, user_id, payment_month, amount, payment_status, created_at, updated_at)
VALUES
  ('1', '1', CURRENT_DATE - INTERVAL '29' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '29' DAY, CURRENT_TIMESTAMP - INTERVAL '29' DAY),
  ('2', '1', CURRENT_DATE - INTERVAL '28' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '28' DAY, CURRENT_TIMESTAMP - INTERVAL '28' DAY),
  ('3', '1', CURRENT_DATE - INTERVAL '27' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '27' DAY, CURRENT_TIMESTAMP - INTERVAL '27' DAY),
  ('4', '1', CURRENT_DATE - INTERVAL '26' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '26' DAY, CURRENT_TIMESTAMP - INTERVAL '26' DAY),
  ('5', '1', CURRENT_DATE - INTERVAL '25' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '25' DAY, CURRENT_TIMESTAMP - INTERVAL '25' DAY),
  ('6', '1', CURRENT_DATE - INTERVAL '24' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '24' DAY, CURRENT_TIMESTAMP - INTERVAL '24' DAY),
  ('7', '1', CURRENT_DATE - INTERVAL '23' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '23' DAY, CURRENT_TIMESTAMP - INTERVAL '23' DAY),
  ('8', '1', CURRENT_DATE - INTERVAL '22' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '22' DAY, CURRENT_TIMESTAMP - INTERVAL '22' DAY),
  ('9', '1', CURRENT_DATE - INTERVAL '21' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '21' DAY, CURRENT_TIMESTAMP - INTERVAL '21' DAY),
  ('10', '1', CURRENT_DATE - INTERVAL '20' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '20' DAY, CURRENT_TIMESTAMP - INTERVAL '20' DAY),
  ('11', '1', CURRENT_DATE - INTERVAL '19' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '19' DAY, CURRENT_TIMESTAMP - INTERVAL '19' DAY),
  ('12', '1', CURRENT_DATE - INTERVAL '18' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '18' DAY, CURRENT_TIMESTAMP - INTERVAL '18' DAY),
  ('13', '1', CURRENT_DATE - INTERVAL '17' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '17' DAY, CURRENT_TIMESTAMP - INTERVAL '17' DAY),
  ('14', '1', CURRENT_DATE - INTERVAL '16' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '16' DAY, CURRENT_TIMESTAMP - INTERVAL '16' DAY),
  ('15', '1', CURRENT_DATE - INTERVAL '15' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '15' DAY, CURRENT_TIMESTAMP - INTERVAL '15' DAY),
  ('16', '1', CURRENT_DATE - INTERVAL '14' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '14' DAY, CURRENT_TIMESTAMP - INTERVAL '14' DAY),
  ('17', '1', CURRENT_DATE - INTERVAL '13' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '13' DAY, CURRENT_TIMESTAMP - INTERVAL '13' DAY),
  ('18', '1', CURRENT_DATE - INTERVAL '12' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '12' DAY, CURRENT_TIMESTAMP - INTERVAL '12' DAY),
  ('19', '1', CURRENT_DATE - INTERVAL '11' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '11' DAY, CURRENT_TIMESTAMP - INTERVAL '11' DAY),
  ('20', '1', CURRENT_DATE - INTERVAL '10' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '10' DAY, CURRENT_TIMESTAMP - INTERVAL '10' DAY),
  ('21', '1', CURRENT_DATE - INTERVAL '9' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '9' DAY, CURRENT_TIMESTAMP - INTERVAL '9' DAY),
  ('22', '1', CURRENT_DATE - INTERVAL '8' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '8' DAY, CURRENT_TIMESTAMP - INTERVAL '8' DAY),
  ('23', '1', CURRENT_DATE - INTERVAL '7' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '7' DAY, CURRENT_TIMESTAMP - INTERVAL '7' DAY),
  ('24', '1', CURRENT_DATE - INTERVAL '6' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '6' DAY, CURRENT_TIMESTAMP - INTERVAL '6' DAY),
  ('25', '1', CURRENT_DATE - INTERVAL '5' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '5' DAY, CURRENT_TIMESTAMP - INTERVAL '5' DAY),
  ('26', '1', CURRENT_DATE - INTERVAL '4' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '4' DAY, CURRENT_TIMESTAMP - INTERVAL '4' DAY),
  ('27', '1', CURRENT_DATE - INTERVAL '3' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '3' DAY, CURRENT_TIMESTAMP - INTERVAL '3' DAY),
  ('28', '1', CURRENT_DATE - INTERVAL '2' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '2' DAY, CURRENT_TIMESTAMP - INTERVAL '2' DAY),
  ('29', '1', CURRENT_DATE - INTERVAL '1' DAY, 0.60, 'pending', CURRENT_TIMESTAMP - INTERVAL '1' DAY, CURRENT_TIMESTAMP - INTERVAL '1' DAY),
  ('30', '1', CURRENT_DATE, 0.60, 'pending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 生成一些已缴纳的记录
INSERT INTO dues_payments (id, user_id, payment_month, amount, payment_method, payment_status, payment_date, created_at, updated_at)
VALUES
  ('31', '1', CURRENT_DATE - INTERVAL '31' DAY, 0.60, 'online', 'paid', CURRENT_TIMESTAMP - INTERVAL '30' DAY, CURRENT_TIMESTAMP - INTERVAL '31' DAY, CURRENT_TIMESTAMP - INTERVAL '30' DAY),
  ('32', '1', CURRENT_DATE - INTERVAL '32' DAY, 0.60, 'online', 'paid', CURRENT_TIMESTAMP - INTERVAL '31' DAY, CURRENT_TIMESTAMP - INTERVAL '32' DAY, CURRENT_TIMESTAMP - INTERVAL '31' DAY),
  ('33', '1', CURRENT_DATE - INTERVAL '33' DAY, 0.60, 'online', 'paid', CURRENT_TIMESTAMP - INTERVAL '32' DAY, CURRENT_TIMESTAMP - INTERVAL '33' DAY, CURRENT_TIMESTAMP - INTERVAL '32' DAY);
